### ISSUE TITLE
`require': cannot load such file -- /lib/zorder

### ISSUE THREAD

**Issue by gloaysa** [masonhale/Starfighter-Gosu-Tutorial#1]
When starting Main.rb I got that error. I just fixed it changing 'require' for 'require_relative' in lines from 4 to 8 as I read recommended [here](http://extensions.rubyforge.org/rdoc/classes/Kernel.html).

I'm new to programming and this is the first time that I fix something that it's not mine, I hope I did it right.

**Comment by masonhale** [comment]
Hi @gloaysa -- thanks for the report. Can you submit that fix as a pull request?
A pull request is way for you to submit a code fix in a way that is easy for me to accept and merge.
Here's a guide with more explanation: https://help.github.com/articles/about-pull-requests/

One more tip -- you would need to submit a pull request from a fork of the repository. Since you have probably already cloned the repo to your local machine, you would need to push your clone to your own github account (thereby creating a fork), then submit the pull request from your fork. It's sounds more complicated that it really is. And it is something worthwhile to learn. This article has more detail: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by masonhale** [comment]
I noticed you had already created a fork, so I was able to create a pull request from you fork. The fix has been merged. Thank you for your submission! You are now listed as a contributor: https://github.com/masonhale/Starfighter-Gosu-Tutorial/graphs/contributors

Fixed by #2
